### ISSUE TITLE
implicit declaration of function ‘BN_GF2m_mod_mul’

### ISSUE THREAD

**Issue by ryanvade** [aws/aws-iot-device-sdk-cpp-v2#59]
I'm trying to build on Fedora 30 with OpenSSL 1.1.1c and am getting the following error:
```
/home/ryan/Source/Repos/aws-iot-sdk-c++/aws-crt-cpp-build/deps/build/src/S2N/pq-crypto/bike/openssl_utils.c: In function ‘ossl_cyclic_product’:
/home/ryan/Source/Repos/aws-iot-sdk-c++/aws-crt-cpp-build/deps/build/src/S2N/pq-crypto/bike/openssl_utils.c:46:8: error: implicit declaration of function ‘BN_GF2m_mod_mul’; did you mean ‘BN_mod_mul’? [-Werror=implicit-function-declaration]
   46 |    if (BN_GF2m_mod_mul(r, a, b, m, bn_ctx) == 0) {
      |        ^~~~~~~~~~~~~~~
      |        BN_mod_mul
/home/ryan/Source/Repos/aws-iot-sdk-c++/aws-crt-cpp-build/deps/build/src/S2N/pq-crypto/bike/openssl_utils.c: In function ‘ossl_add’:
/home/ryan/Source/Repos/aws-iot-sdk-c++/aws-crt-cpp-build/deps/build/src/S2N/pq-crypto/bike/openssl_utils.c:132:8: error: implicit declaration of function ‘BN_GF2m_add’ [-Werror=implicit-function-declaration]
  132 |    if (BN_GF2m_add(r, a, b) == 0) {
      |        ^~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[5]: *** [CMakeFiles/s2n.dir/build.make:414: CMakeFiles/s2n.dir/pq-crypto/bike/openssl_utils.c.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:73: CMakeFiles/s2n.dir/all] Error 2
gmake[3]: *** [Makefile:130: all] Error 2
gmake[2]: *** [CMakeFiles/S2N.dir/build.make:113: build/src/S2N-stamp/S2N-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:298: CMakeFiles/S2N.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
CMake Error at CMakeLists.txt:80 (message):
  Failed to build aws crt libraries.


-- Configuring incomplete, errors occurred!

```

**Comment by JonathanHenson** [comment]
Is that the system openssl or one you installed?

**Comment by ryanvade** [comment]
System installed

**Comment by JonathanHenson** [comment]
So the good news is that the post quantum code can be disabled via a cmake arg. The bad news is that the build matrix of openssl libcrypto versions is basically unbounded and we haven’t quite gotten a handle on how to 100% prevent breakages from time to time (sorry about that). I’ll bring this up with the s2n team and get a path forward on how to prevent this in the future.

**Comment by JonathanHenson** [comment]
okay, just checked and this is definitely an openssl versioning issue. In the meantime, I recommend passing the: -DUSE_S2N_PQ_CRYPTO=OFF argument to cmake

**Comment by JonathanHenson** [comment]
alternatively you can use any openssl specified here:
https://github.com/awslabs/s2n/blob/master/docs/USAGE-GUIDE.md

**Comment by JonathanHenson** [comment]
just an update, I'm looking into how to work around this, trying to figure out if it's an openssl issue or not. We did find this but it's older:

https://bugzilla.redhat.com/show_bug.cgi?id=815600

**Comment by ryanvade** [comment]
I'll try to rebuild this tomorrow, thanks @JonathanHenson

**Comment by ryanvade** [comment]
I tried adding `-DUSE_S2N_PQ_CRYPTO=OFF` and unfortunately I ran into the same problem
